#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /
    controller: App\Controller\HomeController::index
asset:
    path: /resize/{width}/{height}/{path}
    controller: App\Controller\AssetController::show
    requirements:
        width: '\d+'
        height: '\d+'
        path: .+
