#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
    path: /
    controller: App\Controller\HomeController::index
asset:
    path: /img/{path}
    controller: App\Controller\AssetController::show
